# Network configuration
host: "192.168.1.155"
port: 5555

# Network performance settings
buffer_size: 16384
timeout: 10.0  # Connection timeout in seconds
max_message_size: 10485760 # 10MB
send_retries: 3
retry_sleep_duration: 1
initial_name_timeout: 5.0
accept_timeout: 1.0
connection_attempt_window: 60
max_connections_per_ip: 5
client_timeout: 30.0 # Client timeout in seconds

# Keepalive settings
keepalive:
  enabled: True
  interval: 30.0
  timeout: 10.0
  tcp_keepidle: 30
  tcp_keepintvl: 1
  tcp_keepcnt: 3

protocol:
  player_id_prefix: "ID:"
  username_taken_message: "USERNAME_TAKEN"
  ping_message: "PING"
  pong_message: "PONG"
  server_full_message: "SERVER_FULL"