# Player configuration
start_velocity: 10

# Size configuration (in game units)
size:
  newborn: 10      # Starting size of a new player
  adult: 30        # Maximum size a player can grow to
  growth_duration: 300  # Time in seconds to reach adult size

# Visual appearance
colors:
  - [255, 0, 0]      # red
  - [255, 128, 0]    # orange
  - [255, 255, 0]    # yellow
  - [128, 255, 0]    # lime
  - [0, 255, 0]      # green
  - [0, 255, 128]    # mint
  - [0, 255, 255]    # cyan
  - [0, 128, 255]    # light blue
  - [0, 0, 255]      # blue
  - [128, 0, 255]    # purple
  - [255, 0, 255]    # magenta
  - [255, 0, 128]    # pink
  - [128, 128, 128]  # gray
  - [0, 0, 0]        # black

